version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "${PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
    ports:
      - "5432:${PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "${DB_NAME}"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s  

  recommender:
    build: .
    ports:
      - "9091:5000"
    environment:
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_APP: main
      DB_PORT: ${DB_PORT}
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_HOST: "db"
    depends_on:
      db:
        condition: service_healthy