version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "5050:5050"
    environment:
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_APP: front_api
    depends_on:
      - db
